# Generated by Django 4.1.2 on 2022-11-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0002_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="Contraseña"),
        ),
    ]
