# Generated by Django 4.1.2 on 2022-11-23 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Type",
            fields=[
                ("type_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type_name",
                    models.CharField(max_length=30, verbose_name="Tipo de Producto"),
                ),
            ],
            options={
                "verbose_name": "Tipo",
                "verbose_name_plural": "Tipos",
                "db_table": "type",
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                ("warehouse_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "warehouse_name",
                    models.CharField(max_length=30, verbose_name="Nombre de Bodega"),
                ),
            ],
            options={
                "verbose_name": "Bodega",
                "verbose_name_plural": "Bodegas",
                "db_table": "warehouse",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "product_name",
                    models.CharField(max_length=30, verbose_name="Nombre de Producto"),
                ),
                (
                    "product_description",
                    models.CharField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Descripción de Producto",
                    ),
                ),
                (
                    "product_stock",
                    models.IntegerField(verbose_name="Stock de Producto"),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventario.type",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventario.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "db_table": "product",
            },
        ),
    ]
