# Generated by Django 4.1.2 on 2022-11-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventario",
            "0002_alter_product_product_description_alter_product_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(
                max_length=30, unique=True, verbose_name="Nombre de Producto"
            ),
        ),
    ]
